# Manipulación de N-dimensional arrays en Python 

## Introducción a NumPy N-dimensional arrays (ndarray para abreviar)

[The N-dimensional array](https://numpy.org/doc/stable/reference/arrays.ndarray.html)

**ndarray** es la forma más usual para almacenar datos y trabajar con ellos
 en el módulo numpy de Python.

 Para fijar ideas, podemos imaginar que un **ndarray** es simplemente un vector 
 o una matriz.

 Veamos cómo se crea un **ndarray**

In [1]:
# importamos el módulo numpy the Python

import numpy as np

In [2]:
# definimos un vector de 3 componentes (1d-array)
x = np.array([1, 4, 3])
print(x)
print(type(x)) # tipo de dato

# veamos algunos atributos (características) del array
print(x.shape) # forma o dimensión del array
print(x.size)  # tamaño del array
print(x.dtype) # tipo de datos que contiene


[1 4 3]
<class 'numpy.ndarray'>
(3,)
3
int32


In [3]:
# definimos un matriz (2d-array)
y = np.array([[1, 4, 3], [9, 2, 7]])
print(y)
print(type(y)) # tipo de dato

# veamos algunos **atributos** (características) del array
print(y.shape) # forma o dimensión del array
print(y.size)  # tamaño del array
print(y.dtype) # tipo de datos que contiene


[[1 4 3]
 [9 2 7]]
<class 'numpy.ndarray'>
(2, 3)
6
int32


Algunas funciones usuales para crear un ndarray son:

In [4]:
# array de ceros de tamaño especificado
a = np.zeros([3,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# array de unos de tamaño especificado
b = np.ones([5])
print(b)


[1. 1. 1. 1. 1.]


In [6]:
# array donde se especifica el inicio, el final (no incluido) y el paso
c = np.arange(1, 5, 0.5)
print(c)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [7]:
# para el caso de que el array contenga números complejos
array_complex = 1j * np.arange(5)
print(array_complex)

# otro ejemplo
z = np.ones(4, dtype=complex) * 2
print(z)

[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[2.+0.j 2.+0.j 2.+0.j 2.+0.j]


In [8]:
# array donde se especifica el inicio, final (incluido) y el número de 
# elementos equiespaciados
d = np.linspace(0, 1, 10)
print(d)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Combinando ndarrays: Apilamiento (**stack**) horizontal y vertical.

En muchas ocasiones es necesario apilar datos de forma horizontal o vertical.

In [9]:
# creamos un primer array
a1 = np.array([1, 2, 3])
print(a1)
# creamos un segundo array
a2 = np.array([4, 5, 6])
print(a2)
# vertical stack (apilamiento vertical)
a3 = np.vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [10]:
# horizontal stack (apilamiento horizontal)
a4 = np.hstack((a1, a2))
print(a4)
print(a4.shape)

[1 2 3 4 5 6]
(6,)


En ocasiones, los datos a estudiar aparecen en otra estructura de datos, por 
ejemplo en el tipo **lista** . Las listas son colecciones indexadas de datos.
Se escriben entre corchetes con sus elementos separados por comas. 

Para **transformar una lista en un ndarray** :

In [11]:
lista = [1, 2, 3] # esto es una lista en Python
print(lista)
print(type(lista))

vector = np.array(lista) # convertimos la lista en un 1d-array (vector)
print(vector)
print(type(vector))

[1, 2, 3]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>


In [12]:
# Otra lista (de lista) de datos
data = [[11, 22],
[33, 44],
[55, 66]]
print(data)
print(type(data))

# convertimos la lista en un 2d-array (matriz)
data = np.array(data)
print(data)
print(type(data))
print(data.shape)

[[11, 22], [33, 44], [55, 66]]
<class 'list'>
[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>
(3, 2)


Otro tipo de datos son las **tuplas**. Muy similares a las listas, pero una vez 
creada una tupla, sus elementos no se pueden cambiar. Las tuplas son inmutables. Es habitual 
usarlas para almacenar los datos de entrenamiento y test en algoritmos de Machine Learning.
Se escriben entre paréntesis con sus elementos separados por comas 

Para **transformar tuplas en ndarrays** : 

In [13]:
tupla = (1, 2, 3) # esto es una tupla en Python
print(tupla)
print(type(tupla))

vector = np.array(tupla) # convertimos la tupla en un 1d-array (vector)
print(vector)
print(type(vector))

(1, 2, 3)
<class 'tuple'>
[1 2 3]
<class 'numpy.ndarray'>


## [Array Indexing](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html)

In [14]:
# índices en 1d-arrays
data = np.array([11, 22, 33, 44, 55])
# numeramos las compnentes del array empezando desde **cero** 
# accedemos a los elementos con corchetes sobre el array
print(data[0])
print(data[4])

# print(data[5]) ## error pues no tenemos ningún elemento

# también podemos usar índices negativos:
# -1 es el último elemento del arrary, -2 el penúltimo, etc.
print(data[-1])
print(data[-5])


11
55
55
11


In [15]:
# índices en 2d-arrays
data = np.array(
    [[11, 22],
    [33, 44],
    [55, 66]]
    )
print(data)
# usamos el criterio usual de filas, columnas, pero empezando en cero
print(data[0, 0])  # dato en posisión [0, 0]
print(data[0, :])  # fila 0, todos los datos
print(data[:, 1])  # todos los datos de la columna 1
 

[[11 22]
 [33 44]
 [55 66]]
11
[11 22]
[22 44 66]


## [Array Slicing](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.indexing.html)

In [16]:
# cortar (slice) 1d-arrays
data = np.array([11, 22, 33, 44, 55])
print(data)
# data[from:to] el corte va desde el dato *from* y acaba justo antes de *to*
print(data[1:4])
# también con índices negativos
print(data[-2: ]) # desde -2 hasta el final

[11 22 33 44 55]
[22 33 44]
[44 55]


En Machine Learning es habitual separar todos  los datos en las llamadas
**features** (características, denotadas por X) y **labels** (etiquetas, y). 
Por ejemplo, las features pueden ser imágenes (números que asignan a cada pixel 
un tono de  color) y los labels la etiqueta de las imágenes (coche, moto, etc.).
Todos los datos aparecen dentro de una matriz y habitualmente hay que cortar (slice) los datos.
Veamos cómo hacer esto.

In [17]:
# cortar (slice) 2d-arrays
data = np.array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]]
    )
print(data)

# las features X serán todas las filas y columnas excepto la última columna
# las labels serán todas las filas y la última columna

X, y = data[:, :-1], data[:, -1]
print(f"X =\n {X}")
print(f"y =\n {y}")


[[11 22 33]
 [44 55 66]
 [77 88 99]]
X =
 [[11 22]
 [44 55]
 [77 88]]
y =
 [33 66 99]


También es habitual en Machine Learning separar los datos en dos subconjuntos:
uno lo usaremos para entrenar un modelo **training dataset** y el otro para 
chequear la bondad del modelo **test dataset**.
Veamos un ejemplo.

In [18]:
data = np.array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]]
    )
print(data)
# training dataset serán todas las filas desde el principio hasta split
# test dataset serán todas las filas empezado desde split y hasta el final
split = 2
train, test = data[:split, :], data[split:, :]
print(f"train dataset =\n {train}")
print(f"test dataset =\n {test}")

[[11 22 33]
 [44 55 66]
 [77 88 99]]
train dataset =
 [[11 22 33]
 [44 55 66]]
test dataset =
 [[77 88 99]]


## [Array Reshape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html)

Después de cortar (slice) los datos es habitual tener que cambiar la forma de 
dichos datos para que se adapten a los requerimientos de algunas librerías de 
tratamiento de datos de Python (scikit-learn, keras, etc.).
Por ejemplo, estructurar los datos de un 1d-array como un 2d-array.
Veamos algunos ejemplos.

In [19]:
# Empezemos viendo algunas data shape (formas de datos)

data = np.array([11, 22, 33, 44, 55])
print(data)
print(data.shape) # devuelve una tupla con el número de elmentos del 1d-array

# introducimos una lista
data = [
    [11, 22], 
    [33, 44],
    [55, 66]
    ]
# convertimos la lista en un 2d-array
data = np.array(data)
print(data)
print(data.shape) # nos devuelve una tupla con el número de filas y de columnas

print(f"número de las filas = {data.shape[0]}")
print(f"número de columnas = {data.shape[1]}")

# fila = dimensión 0, columna = dimensión 1

[11 22 33 44 55]
(5,)
[[11 22]
 [33 44]
 [55 66]]
(3, 2)
número de las filas = 3
número de columnas = 2


In [20]:
# convertimos un 1d-array (vector fila) en un 2d-array (vector columna)
data = np.array([11, 22, 33, 44, 55])
print(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data)
print(data.shape)

[11 22 33 44 55]
(5,)
[[11]
 [22]
 [33]
 [44]
 [55]]
(5, 1)


In [21]:
# convertimos un 2d-array en un 3d-array
# un ejemplo de la utilidad de convertir un 2d-array en un 3d-array podría ser
# el siguiente: los datos representan la feature "fuerza". Cada fila contiene 
# un dato medido (sample) de la fuera (vector de 3 componentes). Reagrupamos 
# los datos guardándolos en un archivador (3d-array) que, de momento, sólo 
# contiene una carpeta (2d-array) donde guardamos los datos de la fuerza (1d-array) 

# lista de datos
data = [[11, 22, 3],
[33, 44, 46],
[55, 66, 76]]
# convertimos la lista en array
data = np.array(data)
print(data)
print(data.shape)
# convertimos el 2d-array en un 3d-array
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data)
print(data.shape)

[[11 22  3]
 [33 44 46]
 [55 66 76]]
(3, 3)
[[[11]
  [22]
  [ 3]]

 [[33]
  [44]
  [46]]

 [[55]
  [66]
  [76]]]
(3, 3, 1)


 Añadir dimensiones con `None`

En NumPy es frecuente necesitar cambiar la forma de un array para que pueda operar correctamente con otros arrays. Una forma muy cómoda de hacerlo es usando `None` dentro de los corchetes.

Por ejemplo, si tenemos un vector

$$
u = (1,2,3),
$$

NumPy lo interpreta como un array de una sola dimensión, cuya forma es `(3,)`.

Si queremos convertirlo en un vector columna, podemos escribir:

```python
u[:, None]
```

Esto añade una nueva dimensión en la segunda posición.

In [22]:

u = np.array([1, 2, 3])

print(f"u = {u}")
print(f"shape de u = {u.shape}")

# Añadimos una nueva dimensión para convertirlo en vector columna
u_columna = u[:, None]

print(f"u_columna =\n {u_columna}")
print(f"shape de u_columna = {u_columna.shape}")

u = [1 2 3]
shape de u = (3,)
u_columna =
 [[1]
 [2]
 [3]]
shape de u_columna = (3, 1)


## [Array Broadcasting](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html)

Podemos sumar dos vectores de la misma dimensión, pero no sumar una matriz a un 
vector. Sin embargo, en Ciencia de Datos, a menudo tenemos que sumar a una 
matriz un vector.

Por ejemplo, si $A = (A_{ij})$ es una matriz y $b = (b_j)$ un vector, entonces
$C = A + b$, representa la matriz de entradas $C_{ij} = A_{ij} + b_j$, donde el 
 vector $b$ se añade a cada fila de la matriz $A$. Esto elimina la necesidad de 
 definir una matriz donde el vector $b$ se copia en cada fila de la nueva matriz.
 Este copiado implícito del vector $b$ en varias localizaciones se llama
 **broadcasting** (algo sí como difusión, en español). Veamos algunos ejemplos. 

In [23]:
# broadcast escalar en un 1d-array
a = np.array([1, 2, 3])
print(a)
b = 2
print(b)
# broadcast
c = a + b
print(c)

# igual pero en un 2d-array
A = np.array([
    [1, 2, 3],
    [1, 1, 1]]
    )
print(A)

b = 2
print(b)
# broadcast
C = A + b
print(C)

# broadcast 1d array en 2d-array

A = np.array([ 
    [1, 2, 3], 
    [1, 1, 1]]
    )
print(A)

b = np.array([1, 2, 3])
print(b)
# broadcast
C = A + b
print(C)

[1 2 3]
2
[3 4 5]
[[1 2 3]
 [1 1 1]]
2
[[3 4 5]
 [3 3 3]]
[[1 2 3]
 [1 1 1]]
[1 2 3]
[[2 4 6]
 [2 3 4]]


La utilidad de `None` se ve especialmente bien cuando queremos hacer operaciones entre vectores usando broadcasting.

Por ejemplo, si queremos sumar cada elemento de un vector columna con cada elemento de un vector fila:

In [24]:
u = np.array([1, 2, 3])
v = np.array([10, 20, 30, 40])

# Convertimos u en vector columna
u_columna = u[:, None]

print(f"u_columna =\n{u_columna}")
print(f"shape de u_columna = {u_columna.shape}")

print(f"v =\n{v}")
print(f"shape de v = {v.shape}")

S = u_columna + v

print(f"S =\n{S}")
print(f"shape de S = {S.shape}")

u_columna =
[[1]
 [2]
 [3]]
shape de u_columna = (3, 1)
v =
[10 20 30 40]
shape de v = (4,)
S =
[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]
shape de S = (3, 4)


In [25]:
# limitaciones del broadcasting
A = np.array([
[1, 2, 3],
[1, 2, 3]])
print(A.shape)
# define one-dimensional array
b = np.array([1, 2])
print(b.shape)
# attempt broadcast. Error: el 1d-array tiene 2 elementos y la matriz 3 columnas
C = A + b
print(C)

(2, 3)
(2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 