# Práctica sobre Tensores en Ciencia de Datos



El fichero la_manga.jpg contiene dos fotos de La Manga del Mar Menor, una de los años 60 y otra actual. 

![imagen de La Manga del Mar Menor en los años 60 y en la actualidad](../data/la_manga.jpg)

Carga dicho fichero y convierte la imagen en un tensor. A continuación, imprime por pantalla el tensor asociado a la imagen y guárdalo en la carpeta data con el nombre **tensor_la_manga.npy**



In [15]:
# Completar aquí

import numpy as np

from PIL import Image

img = Image.open("../data/la_manga.jpg")
imgarray = np.array(img)

print(f"tensor asociado a la imagen = \n {imgarray}")

# guardamos el tensor en un fichero de tipo np
np.save("../data/tensor_la_manga.npy", imgarray)  # sin comprimir

    
# Fin Completar aquí ------------------------------------


tensor asociado a la imagen = 
 [[[192 192 192]
  [190 190 190]
  [189 189 189]
  ...
  [149 176 195]
  [149 176 195]
  [149 176 195]]

 [[193 193 193]
  [191 191 191]
  [189 189 189]
  ...
  [148 175 194]
  [148 175 194]
  [148 175 194]]

 [[194 194 194]
  [192 192 192]
  [190 190 190]
  ...
  [146 173 192]
  [146 173 192]
  [146 173 192]]

 ...

 [[184 184 184]
  [143 143 143]
  [121 121 121]
  ...
  [ 59  89  81]
  [ 61  91  83]
  [ 61  91  83]]

 [[174 174 174]
  [133 133 133]
  [119 119 119]
  ...
  [ 63  94  86]
  [ 65  96  88]
  [ 66  97  89]]

 [[160 160 160]
  [123 123 123]
  [117 117 117]
  ...
  [ 67  98  90]
  [ 70 101  93]
  [ 69 102  93]]]


Calcula la forma y dimensión del tensor generado. 

In [16]:
# Completar aquí

print(f"forma del tensor generado =  {imgarray.shape}")
print(f"dimensión del tensor generado = {imgarray.ndim}")


# Fin Completar aquí ------------------------------------

forma del tensor generado =  (720, 960, 3)
dimensión del tensor generado = 3


Utiliza la técnica de **slicing** que vimos en la práctica 3 para generar dos vectores. Uno de ellos, denotado **v1** se ha de corresponder con la primera fila del tensor que ves por pantalla; el segundo vector, **v2**, está formado por la segunda fila que ves por pantalla.  

In [17]:
# Completar aquí

v1 = np.array(np.copy(imgarray[0, 0, :]))
print(f"v1 = {v1}")

v2 = np.array(np.copy(imgarray[0, 1, :]))
print(f"v2 = {v2}")

# Fin Completar aquí ------------------------------------

v1 = [192 192 192]
v2 = [190 190 190]


Calcula:

1) el producto tensorial de **v1** y **v2**

2) el producto de Hadamard de **v1** y **v2**

3) el producto escalar de **v1** y **v2**

In [18]:
# Completar aquí

print(f"v1 ⊗ v2 = \n {np.tensordot(v1, v2, axes=0)}")
print(f"v1 * v2 = {v1 * v2}")
print(f"producto escalar = {np.tensordot(v1, v2, axes=1)}")

# Fin Completar aquí ------------------------------------

v1 ⊗ v2 = 
 [[128 128 128]
 [128 128 128]
 [128 128 128]]
v1 * v2 = [128 128 128]
producto escalar = 128


Introduce manualmente, usando **np.array()**, los vectores **v1** y **v2** anteriores y denótaos por **z1** y **z2**, respectivamente.

A contrinuación ealiza los mismos cálculos (producto tensorial, producto de Hadamard y producto escalar) con los vectores **z1** y **z2**.

In [19]:
# Completar aquí

z1 = np.array([192, 192, 192])
print(f"z1 = {z1}")

z2 = np.array([190, 190, 190])
print(f"z2 = {z2}")


print(f"z1 ⊗ z2 = \n {np.tensordot(z1, z2, axes=0)}")

print(f"v1 * v2 = {z1 * z2}")
print(f"producto escalar = {np.tensordot(z1, z2, axes=1)}")

# Fin Completar aquí ------------------------------------

z1 = [192 192 192]
z2 = [190 190 190]
z1 ⊗ z2 = 
 [[36480 36480 36480]
 [36480 36480 36480]
 [36480 36480 36480]]
v1 * v2 = [36480 36480 36480]
producto escalar = 109440


Como puedes ver, obtienes resultados distintos. 

Busca una explicación convincente para esta discrepancia de resultados.
Te puede resultar útil estudiar los atributos **shape**, **type** y **dtype** de los vectores **v1**, **v2**, **z1** y **z2**.

Investiga y dí todo lo que sepas sobre este asunto.

In [20]:
# Completar aquí

print(v1.shape)
print(type(v1))
print(v1.dtype)

print(v2.shape)
print(type(v2))
print(v2.dtype)

print(type(z1))
print(z1.shape)
print(z1.dtype)

print(type(z2))
print(z2.shape)
print(z2.dtype)

# Observamos que la única diferencia es dtype: los datos 
# que provienen de imágenes se almacenan en formato unint8, 
# que son enteros sin signo de 8 bits
# Podemos convertirlos a int64 así:
# v1 = v1.astype(int)
# print(v1.dtype)

# Fin Completar aquí ------------------------------------

(3,)
<class 'numpy.ndarray'>
uint8
(3,)
<class 'numpy.ndarray'>
uint8
<class 'numpy.ndarray'>
(3,)
int64
<class 'numpy.ndarray'>
(3,)
int64
