# N-dimensional arrays en Python


## Introducción

Partimos de tu número de DNI, que debe contener 9 dígitos.
DNI = abcdefgh  . Por ejemplo, DNI = 23982606

Introduce tu DNI en forma de 1d-array e imprimelo junto con sus atributos forma, tamaño y tipo

In [59]:
# Completar aquí

import numpy as np

DNI = np.array([2, 3, 9, 8, 2, 6, 0, 6])

print(f"DNI = {DNI}")
print(DNI.shape) # forma o dimensión del array
print(DNI.size)  # tamaño del array
print(DNI.dtype) # tipo de datos que contiene

# Fin Completar aquí ------------------------------------


DNI = [2 3 9 8 2 6 0 6]
(8,)
8
int64


Define e imprimer los siguientes ndarrays:

1) Una matriz cuadrada de unos y de tamaño el dígito más grande de tu DNI.

2) Una matriz de tamaño $m\times n$, donde $m$ es el dígito más pequeño (excluido el $0$) de tu DNI, y $n$ el dígito más grande, cuyas entradas sean todo cero.

3) Un vector cuyo primer elemento sea el dígito más pequeño de tu DNI, cuyo último elemento sea el dígito más grande, y que contenga $5$ elementos equiespaciados.

4) Un vector cuyo primer elemento sea el dígito más pequeño de tu DNI, el último el dígito más grande y donde cada elemento del array esté separado del siguiente en una unidad. 

In [60]:
# Completar aquí

M_unos = np.ones([9, 9])
print(f"M_unos = \n {M_unos}")

M_ceros = np.zeros([2, 9])
print(f"M_ceros = \n {M_ceros}")

vector_1 = np.linspace(0, 9, 5)
print(f"vector_1 = {vector_1}")

vector_2 = np.arange(0, 10, 1)
print(f"vector_2 = {vector_2}")

# Fin Completar aquí ------------------------------------

M_unos = 
 [[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
M_ceros = 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]
vector_1 = [0.   2.25 4.5  6.75 9.  ]
vector_2 = [0 1 2 3 4 5 6 7 8 9]


Apila de manera horizontal los vectores introducidos en los apartados 3) y 4) del apartado anterior.

Calcula el tamaño el array resultante.

In [61]:
# Completar aquí

apila_horizontal = np.hstack((vector_1, vector_2))
print(f"apila_horizontal = {apila_horizontal}")

print(f"size = {apila_horizontal.size}")

# Fin Completar aquí ------------------------------------

apila_horizontal = [0.   2.25 4.5  6.75 9.   0.   1.   2.   3.   4.   5.   6.   7.   8.
 9.  ]
size = 15



Utiliza **vstack** para generar una matriz con dos filas, cada una de las cuales contenga al vector gnerado en el apartado 4) anterior.

Calcula el tipo o forma (shape) del array generado.

In [62]:
# Completar aquí

matriz = np.vstack((vector_2, vector_2))
print(f"matriz = \n {matriz}")

print(f"dimensión = {matriz.shape}")


# Fin Completar aquí ------------------------------------

matriz = 
 [[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
dimensión = (2, 10)


Intenta apilar, también de manera vertical, los vectores de los apartados 3) y 4) anteriores. 

Obtienes un error. ¿A qué se debe este error?

In [ ]:
# Completar aquí

apila_vertical = np.vstack((vector_1, vector_2))

# el error se debe a que los vectores que se intentan apilar
# tienen distinta dimensión

# Fin Completar aquí ------------------------------------

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 10

Introduce tu DNI en formato lita y tupla. Convierte ambos a formato **ndarray** 

In [ ]:
# Completar aquí

DNI_lista = [2, 3, 9, 8, 2, 6, 0, 6]
print(f"DNI_lista = {DNI_lista}")
print(type(DNI_lista))

DNI_lista2array = np.array(DNI_lista) # convertimos la lista en un 1d-array (vector)
print(f"DNI_lista2array = {DNI_lista2array}")
print(type(DNI_lista2array))

DNI_tupla = (2, 3, 9, 8, 2, 6, 0, 6)
print(f"DNI_tupla = {DNI_tupla}")
print(type(DNI_tupla))

DNI_tupla2array = np.array(DNI_tupla) # convertimos la tupla en un 1d-array (vector)
print(f"DNI_tupla2array = {DNI_tupla2array}")
print(type(DNI_tupla2array))

# Fin Completar aquí ------------------------------------

DNI_lista = [2, 3, 9, 8, 2, 6, 0, 6]
<class 'list'>
DNI_lista2array = [2 3 9 8 2 6 0 6]
<class 'numpy.ndarray'>
DNI_tupla = (2, 3, 9, 8, 2, 6, 0, 6)
<class 'tuple'>
DNI_tupla2array = [2 3 9 8 2 6 0 6]
<class 'numpy.ndarray'>


## NumPy arrays: index, slice, reshape, broadcasting, etc.

Introduce tu DNI en la forma de 1d-array.

A continuación, selecciona e imprime la siguiente información de dicho array:

1) el primer elemento
2) el último
3) El que ocupa la segunda posición (empezando desde la izquierda)
4) el que ocupa la antepenúltima 
5) los tres primeros elementos
6) los 4 últimos elementos

In [ ]:
# Completar aquí

DNI = np.array([2, 3, 9, 8, 2, 6, 0, 6])    
print(f"DNI = {DNI}")

print(f"primer elemento = {DNI[0]}")
print(f"último elemento = {DNI[-1]}")
print(f"segundo elemento = {DNI[1]}")
print(f"antepenúltimo elemento = {DNI[-3]}")
print(f"tres primeros elementos = {DNI[:3]}")
print(f"cuatro últimos elementos = {DNI[-4:]}")


# Fin Completar aquí ------------------------------------

Cambia la forma del 1d-array que contiene tu nombre para convertirlo en un 2d-array (matriz) de tamaño $2\times 4$, es decir dos filas y cuatro columnas. 

A continuación, selecciona e imprime los siguientes datos del nuevo 2d-array:

1) la primera fila
2) la segunda columna

In [ ]:
# Completar aquí
DNI_matriz = DNI.reshape(2, 4)
print(f"DNI_matriz = \n {DNI_matriz}")

print(f"primera fila = {DNI_matriz[0, :]}")
print(f"segunda columna = {DNI_matriz[:, 1]}")

# Fin Completar aquí ------------------------------------

Imaginemos que el 2d-array del ejercicio anterior contiene las features $X$ y las labels $y$ de un modelo de Machine Learning. En concreto, $X$ almacena todos los datos excepto la última columna mientras que $y$ contiene los datos de la última columna.

Genera $X$ e $y$.

In [ ]:
# Completar aquí
X, y = DNI_matriz[:, :-1], DNI_matriz[:, -1]
print(f"X =\n {X}")
print(f"y =\n {y}")
# Fin Completar aquí ------------------------------------

Supongamos ahora que queremos separar los datos del 2d-array en dos subconjuntos, un training dataset y un test dataset.

Training dataset será la primera fila y  test dataset será la segunda fila

In [ ]:
# Completar aquí
split = 1
train, test = DNI_matriz[:split, :], DNI_matriz[split:, :]
print(f"train dataset =\n {train}")
print(f"test dataset =\n {test}")
# Fin Completar aquí ------------------------------------

Introduce un escalar que se corresponda con tu nota de entrada al grado de Ciencia e Ingeniería de Datos. A continuación realiza las siguientes operaciones:

1) Suma el escalar al 2d-array anterior
2) Multiplica el escalar al 2d-array anterior
3) Divide el 2d-array por el escalar

In [ ]:
# Completar aquí
nota_entrada = 14

print(f"escalar + matriz =\n {nota_entrada + DNI_matriz}")
print(f"escalar * matriz =\n {nota_entrada * DNI_matriz}")
print(f" matriz / escalar =\n {DNI_matriz / nota_entrada}")
# Fin Completar aquí ------------------------------------